config/routes.rb
Rails.application.routes.draw do

  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  get '/top' => 'homes#top'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  root to: 'homes#top'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
   attribute :title, :string
    attribute :body, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @books = Book.new
  end
  
 
  
  def create
  @book = Book.new(book_params)
   if @book.save
    flash[:error] = "Book was successfully created."
     redirect_to book_path(@book.id)
   else
    @books = Book.all
    render :index
    
   end
  end 
  


   def index
    @books = Book.all
    @book = Book.new
   end

  
  def show
     @book = Book.find(params[:id]) 
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
   if  @book.update(book_params)
    redirect_to book_path(@book.id), notice: "Book was successfully updated."
   else 
    render :edit
   end
  end 
   def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_url, notice: "Book was successfully destroyed." # 投稿一覧画面へリダイレクト  
   end

   
  private
   def book_params
    params.require(:book).permit(:title, :body)
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<head>
<%= stylesheet_link_tag 'new.css' %>
</head>

<div class="errors">
  <% if @book.errors.any? %>
   <h2 class="error"> 
 <%= @book.errors.count %>errors prohibited this book from being saved:
 </h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
  <% end %>
   
<h1>Editing Book</h1>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

  <h4 class="add">
    Title
    <div >
  <%= f.text_field :title %>
    </div>
  </h4>
  <h4 class="add">
    Body
    <div >
        <%= f.text_area :body %>
    </div>
  </h4>
  
    <div class="add">
      <%= f.submit "Update Book"%>
    </div>
<% end %>

    <div class="add">
<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back", books_path %>
   </div>

app/views/books/index.html.erb
<head>
<%= stylesheet_link_tag 'new.css' %>
</head>
<h1>Books</h1>
<table>
  <thead>
    <tr>
    <th>Title</th>
    <th>Body</th>
    <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td class="text">
      <%= book.title %>
      </td>
      <td class="text">
      <%= book.body %>
      </td>
      <td class="text">
  <%= link_to "Show", book_path(book) %>
      </td>
      <td class="text">
  <%= link_to "Edit", edit_book_path(book) %>
      </td>
      <td class="text">
    <%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure？' } %>
      </td>
    </tr>
  </tbody>
  <% end %>
 </table>




<h3>New book</h3>
<!-- form_with部分 -->
<%= form_with model: @book, url:'/books',　method: :post do |f| %>
<div class="errors">
  <% if @book.errors.any? %>
   <h2 class="error"> 
 <%= @book.errors.count %>errors prohibited this book from being saved:
 </h2>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  </div>
<% end %>

  <h4>Title</h4>
  <div class="nil"> 
  <%= f.text_field :title %>
  </div>

  <h4>Body</h4>
  <div class="nil"> 
  <%= f.text_area :body %>
  </div>
  
  <div class="nil"> 
  <%= f.submit "Create Book" %>
  </div>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<p>
<strong>Title:</strong>
<%= @book.title %>
</p>

<p>
 <strong>Body:</strong>
 <%= @book.body %>
</p>


<%= link_to "Edit",edit_book_path(@book.id)%> |
<%= link_to "Back",books_path %>

app/views/homes/top.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>

<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>

<p>印象を共有し交換することができます</p>

<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main>
    <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>